Added homework
JeremyMonarch/my-program-fisrt pull request #6
Opened 2022-05-24 08:26 UTC by JeremyMonarch

Lesson07-strings

2022-05-24 11:29 UTC, sergey-olefir requested changes

2022-05-24 11:29 UTC, sergey-olefir commented on Lesson.07.Strings/Lesson.07.Strings/Program.cs
> +            PrintCharsEqual();
SRP is brocken

2022-05-24 13:06 UTC, JeremyMonarch commented on Lesson.07.Strings/Lesson.07.Strings/Program.cs
> +            PrintCharsEqual();
Edit code

2022-05-29 11:12 UTC, sergey-olefir approved these changes
good job

2022-05-29 11:12 UTC, merged